# Generated by Django 4.2.11 on 2024-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen_perfil',
            field=models.ImageField(max_length=200, upload_to='static/img/perfil/', verbose_name='Imagen de perfil'),
        ),
    ]
