# Generated by Django 4.2.11 on 2024-05-15 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subespecialidades', to='core.especialidad'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.ManyToManyField(to='core.especialidad'),
        ),
    ]
