# Generated by Django 4.2.11 on 2024-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
        ),
    ]
