# Generated by Django 4.2.11 on 2024-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profesional_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='campo',
            field=models.CharField(default='Jurista', max_length=50),
        ),
    ]
