# Generated by Django 4.2.11 on 2024-04-30 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField(default='', max_length=400)),
                ('recomendacion', models.BooleanField(default=True)),
                ('fecha_comentario', models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 35, 20, 712320))),
                ('valoracion', models.IntegerField(default=1)),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('profesional', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profesional')),
            ],
        ),
    ]
