# Generated by Django 4.2.11 on 2024-05-27 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_especialidad_parent_alter_profesional_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField(default='', max_length=400)),
                ('recomendacion', models.BooleanField(default=True)),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('valoracion', models.IntegerField(default=1)),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profesional')),
            ],
        ),
    ]
