# Generated by Django 5.0.3 on 2024-04-22 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_cliente_rename_especilidad_profesional_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesional')),
            ],
        ),
    ]
