# Generated by Django 5.0.3 on 2024-04-22 21:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('usuarios', '0002_cliente_rename_especilidad_profesional_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 23, 0, 5, 483906)),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='recomendacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='texto_comentario',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='comentario',
            name='valoracion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_profesional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesional'),
        ),
    ]
