# Generated by Django 5.0.3 on 2024-04-22 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_fecha_comentario_comentario_id_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='id_profesional',
            new_name='profesional',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 23, 0, 44, 961875)),
        ),
    ]
