# Generated by Django 5.0.3 on 2024-04-22 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_rename_id_cliente_comentario_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 23, 8, 50, 447036)),
        ),
    ]
