# Generated by Django 4.2.11 on 2024-04-29 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profesional_campo'),
        ('comentarios', '0008_alter_comentario_fecha_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 11, 47, 3, 287125)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='profesional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profesional'),
        ),
    ]
