# Generated by Django 4.2.11 on 2024-04-29 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0009_alter_comentario_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 11, 48, 52, 905301)),
        ),
    ]
