# Generated by Django 4.2.11 on 2024-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('precio', models.FloatField()),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE'), ('E', 'ESPERA'), ('C', 'CANCELADA')], max_length=1)),
                ('descripcion', models.TextField(default='', max_length=400, null=True)),
            ],
        ),
    ]
