# Generated by Django 4.2.11 on 2024-04-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('precio', models.FloatField()),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE'), ('A', 'ACEPTADA'), ('R', 'RECHAZADA')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesional')),
            ],
        ),
    ]
