# Generated by Django 4.2.11 on 2024-04-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_cliente_alter_cita_profeisonal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='profeisonal',
            new_name='profesional',
        ),
    ]
